on:
  workflow_call:
    inputs:
      APP_NAME:
        required: true
        type: string
      APP_URL:
        required: true
        type: string
      CF_ORGANIZATION_NAME:
        required: true
        type: string
      CF_SPACE_NAME:
        required: true
        type: string
      NEW_RELIC_APP_NAME:
        type: string
      S3_BUCKET_URL:
        required: true
        type: string
      S3_SERVICE_NAME:
        required: true
        type: string
    secrets:
      CF_USERNAME:
        required: true
      CF_PASSWORD:
        required: true
      NEW_RELIC_LICENSE_KEY:

env:
  APP_NAME: ${{ inputs.APP_NAME }}
  APP_URL: ${{ inputs.APP_URL }}
  CF_USERNAME: ${{ secrets.CF_USERNAME }}
  CF_PASSWORD: ${{ secrets.CF_PASSWORD }}
  CF_ORGANIZATION_NAME: ${{ inputs.CF_ORGANIZATION_NAME }}
  CF_SPACE_NAME: ${{ inputs.CF_SPACE_NAME }}
  NEW_RELIC_APP_NAME: ${{ inputs.NEW_RELIC_APP_NAME }}
  NEW_RELIC_LICENSE_KEY: ${{ secrets.NEW_RELIC_LICENSE_KEY }}
  S3_BUCKET_URL: ${{ inputs.S3_BUCKET_URL }}
  S3_SERVICE_NAME: ${{ inputs.S3_SERVICE_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Install ruby and gem dependencies
        uses: ruby/setup-ruby@360dc864d5da99d54fcb8e9148c14a84b90d3e88
        with:
          bundler-cache: true
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
          cache: 'npm'
      - name: Install node dependencies
        # Fix for installing puppeteer which is a pa11y dependency.
        # Remove when this GitHub issue is resolved: https://github.com/puppeteer/puppeteer/issues/12094
        env:
          NODE_ENV: production
        run: npm ci --timing
      - name: Copy uswds assets
        run: npm run copy-assets
      - name: Replace application URLs for the environment in jekyll config file before building the site
        run: |
          sed -i "s@url: https://analytics\.usa\.gov@url: ${APP_URL}@g" _config.yml
          cat _config.yml
      - name: Bundle javascript for production
        run: npm run build-prod
      - name: Build jekyll site
        run: bundle exec jekyll build
      - name: Install cloud foundry CLI for interacting with cloud.gov
        run: |
          sudo curl -v -L -o cf8-cli-installer_8.7.4_x86-64.deb 'https://packages.cloudfoundry.org/stable?release=debian64&version=8.7.4'
          sudo dpkg -i cf8-cli-installer_8.7.4_x86-64.deb
      - name: Run envsubst on manifest.yml to set environment specific values
        run: |
          mv manifest.yml manifest.yml.src
          envsubst < manifest.yml.src > manifest.yml
          cat manifest.yml
      - name: Run envsubst on nginx.conf to set the S3 bucket URL for the environment
        run: |
          envsubst '${S3_BUCKET_URL}' < nginx.conf.src > nginx.conf
      - name: Login to cloud.gov and deploy
        run: |
          set -e
          # Log into cloud.gov
          cf api api.fr.cloud.gov
          cf login -u $CF_USERNAME -p $CF_PASSWORD -o $CF_ORGANIZATION_NAME -s $CF_SPACE_NAME
          cf push -f "./manifest.yml"
          cf logout
